### ISSUE TITLE
Hugely helpful guide, thank you

### ISSUE THREAD

**Issue by Msturroc** [MRPHarris/compiling-era52arl#1]
I just wanted to say that this guide is incredibly helpful. For the record, I found that the openjpg step and even the miniconda step were not necessary in my case (I have a system-wide installation of python though).  I hope it's OK but I will fork this directory to keep a record of exactly what I did

**Comment by MRPHarris** [comment]
Thanks for letting me know! I've added a note on those steps with a link to this issue.
